### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by Minesraft2** [SnesLover22/Mathews-Collection#1]
Our license is not for the newest version, they are for all versions. Which includes the scripts [here](https://github.com/therealgliz/blooket-hacks), because those were made by me aswell.

**Comment by Minesraft2** [comment]
It's a simple fix, I don't understand why you refuse

**Comment by Minesraft2** [comment]
💀 i just checked the script and it's not even ours

**Comment by SnesLover22** [comment]
LOL imagine just believing I took it? I said I HAD it on my website, but I had changed it when it stopped working a few months ago. Jeez these guys get mad when they think their work is under siege, just like Mojang and Microsoft. smh

**Comment by Minesraft2** [comment]
It's not hard to believe you just took it

**Comment by Minesraft2** [comment]
People do it constantly

**Comment by SnesLover22** [comment]
yeah and its DEFINETLY hard to read over someones comment

**Comment by SnesLover22** [comment]
i think Github is on my side if my repository isn't down yet... they obviously understand what you didn't

**Comment by Minesraft2** [comment]
Github usually takes a week or two before actually doing anything

**Comment by Minesraft2** [comment]
The dmca against rzx was like a month old before he went down

**Comment by SnesLover22** [comment]
![Screenshot 2023-01-22 6 49 45 PM](https://user-images.githubusercontent.com/110874555/213949815-b280c69b-824e-47bb-b24d-be7174c584e8.png)

**Comment by Minesraft2** [comment]
Yea but it's different when the content was clearly bound to a strict licensed and the website is on github

**Comment by SnesLover22** [comment]
idk why you're so serious about a Blooket Hack. You're not even a big company with some meaningful software to the world, it's just a hack for a QUIZ GAME

**Comment by SnesLover22** [comment]
Why have a license, so you only have credit for the blooket hack?

**Comment by Minesraft2** [comment]
Maybe you'd understand after several people try to claim they made something you made

**Comment by Minesraft2** [comment]
I doubt you've ever had that issue

**Comment by SnesLover22** [comment]
that happened to me on many occasions. But I don't really care since they're STUPID LITTLE PROJECTS I did for FUN

**Comment by Minesraft2** [comment]
This isn't a little project

**Comment by Minesraft2** [comment]
Nor am I doing this for fun

**Comment by SnesLover22** [comment]
why then?

**Comment by SnesLover22** [comment]
also:
![Screenshot 2023-01-22 6 56 36 PM](https://user-images.githubusercontent.com/110874555/213950196-9b26fc1f-98b2-4121-97f7-824e0c777021.png)
this is technically illegal against blooket so your license goes against itself

**Comment by Minesraft2** [comment]
It's not illegal against blooket it just goes against the blooket ToS

**Comment by Minesraft2** [comment]
And it's mostly just messing around with blooket code

**Comment by SnesLover22** [comment]
> It's not illegal against blooket it just goes against the blooket ToS

if it goes against blooket, its technically illegal.

**Comment by SnesLover22** [comment]
> 



> And it's mostly just messing around with blooket code

if this is so there's no reason to add a license to it

**Comment by Minesraft2** [comment]
Yea well go to goose about license stuff he's the one who wrote it.

**Comment by Minesraft2** [comment]
Having ownership of something you made isn't a reason to license something?

**Comment by SnesLover22** [comment]
well you didn't make to blooket API, and that's stealing too ya know

**Comment by Minesraft2** [comment]
Only a handful of cheats use the blooket API

**Comment by SnesLover22** [comment]
yeah but they still use it

**Comment by Minesraft2** [comment]
And it's not a little project when over 1000 people a day go to the repo
![image](https://user-images.githubusercontent.com/49218878/213950535-9793c072-db7a-49ad-be9a-f10544057c86.png)

**Comment by Minesraft2** [comment]
And we're not claiming to own the blooket api

**Comment by Minesraft2** [comment]
nor does blooket say we can't use it because then we couldn't use the site

**Comment by SnesLover22** [comment]
I never claimed it was my hack. Pretty sure your license states to not claim the software as ones own. I never did that. I was even telling you I'll give creds to the original creator, you, in return to put it back on my site (plus, I was just asking for help with the damn code not working, either due to you or an update to the blooket API.)

**Comment by SnesLover22** [comment]
> nor does blooket say we can't use it because then we couldn't use the site

blooket says you can't make edits to it, nor use it in any way that goes against their license

**Comment by Minesraft2** [comment]
And I was never the one to try and dmca you, goose and greenlio were. Though the license does say not to republish anything without our permission. And [Blooket's terms](https://www.blooket.com/terms) don't actually say we can't use their code for ingame advantages, just no trying to gain access to the site's original source code and no trying to use any found code to harm or hurt blooket

**Comment by Minesraft2** [comment]
So technically we're not going against Blooket's terms

**Comment by SnesLover22** [comment]
Also, I wouldn't complain if this wasn't stupid, as even though hundreds of people go to your repo, they come from more significant people like YouTubers. I found your repo through a YT vid claiming it was theirs. I looked around and found some did give credits, though I doubt many Youtubers personally asked you for permission. I even asked YOU, the leading creator of the hack for permission to distribute if done by giving credits, but I guess you skimmed over that, did you?

**Comment by SnesLover22** [comment]
As I was senselessly attacked just to ask for help, I tried to ask for some way around the DMCA, but I guess, quote: "messing around with blookets code" is enough to require a license. Your team isn't the first I've had to deal with for shiz like this

**Comment by Minesraft2** [comment]
Most people find my repo through github and google
![image](https://user-images.githubusercontent.com/49218878/213951169-eacb0637-bbe2-4570-9f5c-0331ecbb444d.png)
Maybe it is stupid, and I'm sorry we attacked you. But ownership matters to us.
I did also tell you what you could do so greenlio wouldn't send a dmca

**Comment by Minesraft2** [comment]
But greenlio is a kind of hot head he does whatever he wants whenever

**Comment by SnesLover22** [comment]
> Most people find my repo through github and google ![image](https://user-images.githubusercontent.com/49218878/213951169-eacb0637-bbe2-4570-9f5c-0331ecbb444d.png) Maybe it is stupid, and I'm sorry we attacked you. But ownership matters to us. I did also tell you what you could do so greenlio wouldn't send a dmca

I didn't see that under all the other angry, rude comments against me.

**Comment by Minesraft2** [comment]
And no, I actually did not miss the part where you asked if you could give credits, I thought it was answered by someone else saying no.

**Comment by SnesLover22** [comment]
And now you just filed a DMCA without any proof against me besides a typo. I know many might not go to my site or repo, but it seems like people like you end up killing smaller creators like us. I wasn't even a major threat!

**Comment by Minesraft2** [comment]
The dmca is already canceled, and I'm not really sure what to do about everyone going crazy in the comments.

**Comment by SnesLover22** [comment]
> And no, I actually did not miss the part where you asked if you could give credits, I thought it was answered by someone else saying no.

no it was answered by some other guy telling me "We've dealt with arrogant children like you"

**Comment by SnesLover22** [comment]
> 



> The dmca is already canceled, and I'm not really sure what to do about everyone going crazy in the comments.

I really do hope so because a lot of my newer repos I try to update fail. I couldn't even update my main site.

**Comment by Minesraft2** [comment]
Ok, you're mad that people all gathered up against you. I don't know what to do about that. I don't agree with the way goose and them deal with this kind of stuff, they didn't even bother to check out the repo and confirm if it was our code or not, nor did they try to give a warning here like I did

**Comment by Minesraft2** [comment]
I don't have anything against you or other coders, I have issues with people who try taking my things

**Comment by Minesraft2** [comment]
I'll try to make sure this doesn't happen to you or anyone else again

**Comment by SnesLover22** [comment]
You know, I really want all this to blow over(with everyone else). I'm a scratcher (scratch.mit.edu/users/flipbookman21) and Im kinda used to all this stuff happening. I have a lot of little kids taking my projects and claiming it's their animation/game, and I usually kindly ask them to make changes/ give creds. I've also had my outbreaks too against others, so I know how you feel about ownership of your work. I just don't think this was professionally handled.

**Comment by SnesLover22** [comment]
> I'll try to make sure this doesn't happen to you or anyone else again

Id be very glad if you could do this.

**Comment by SnesLover22** [comment]
> > I'll try to make sure this doesn't happen to you or anyone else again
> 
> Id be very glad if you could do this.

Im already going through enough stuff rn, I don' think i could've handled a dmca, as I was already freaking out about it. I hope we could look over this incident, and forget it happened, maybe even be partners later on in the future. I'm sorry if I caused any trouble.

**Comment by Minesraft2** [comment]
> You know, I really want all this to blow over(with everyone else). I'm a scratcher (scratch.mit.edu/users/flipbookman21) and Im kinda used to all this stuff happening. I have a lot of little kids taking my projects and claiming it's their animation/game, and I usually kindly ask them to make changes/ give creds. I've also had my outbreaks too against others, so I know how you feel about ownership of your work. I just don't think this was professionally handled.

It in fact, was not handled well. The dmca never would've even went through anyway because there's nothing tying it back to my repo. I don't really do partnerships though, there's a small group of scripters and we primarily make things like cheats for sites like Blooket. You could try starting small, like making cheat scripts for popular sites like we do or something and build your way up.

**Comment by Minesraft2** [comment]
It's unlikely we'll add anyone to the council tho

**Comment by SnesLover22** [comment]
> It's unlikely we'll add anyone to the council tho

that's fine, as long as you're not pissed at me or anything. We good?

**Comment by Minesraft2** [comment]
We're good, just tread lightly around goose and greenlio

**Comment by SnesLover22** [comment]
ok, I will

**Comment by Ironbrodiet** [comment]
lol
